# Generated by Django 5.1.6 on 2025-03-08 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0004_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
