# Generated by Django 5.1.6 on 2025-03-08 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0006_alter_doctorsprofileinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'verbose_name': 'Doctors Availabilitie'},
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customize.doctorsprofileinfo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
