# Generated by Django 5.1.6 on 2025-03-08 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0008_alter_doctoravailability_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'active': True, 'admin': False, 'staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availabilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
