# Generated by Django 5.1.6 on 2025-03-08 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0010_alter_doctoravailability_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsprofileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorsprofileinfo',
            name='user',
            field=models.ManyToManyField(related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
