# Generated by Django 5.1.6 on 2025-03-08 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0012_alter_doctoravailability_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customize.doctorsprofileinfo'),
        ),
        migrations.RemoveField(
            model_name='doctorsprofileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorsprofileinfo',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
