# Generated by Django 5.1.6 on 2025-03-08 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0015_remove_doctorsprofileinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsprofileinfo',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
