# Generated by Django 5.1.6 on 2025-03-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0020_alter_doctorsprofileinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customize.doctorsprofileinfo'),
        ),
    ]
