# Generated by Django 5.1.6 on 2025-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0024_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsprofileinfo',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'verbose_name': 'Doctors Availabilitie'},
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'date'), name='unique_doctor_availability'),
        ),
        migrations.DeleteModel(
            name='DoctorsProfileInfo',
        ),
    ]
