# Generated by Django 5.1.6 on 2025-03-08 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0025_remove_doctorsprofileinfo_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_first_name', models.CharField(max_length=100)),
                ('doc_last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='Enter a valid 11-digit phone number (numeric only).', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must consist of exactly 11 digits and be numeric.', regex='^\\d{11}$')])),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='doc-imgs/')),
                ('available', models.BooleanField(blank=True, default=True)),
                ('user', models.OneToOneField(limit_choices_to={'active': True, 'admin': False, 'staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctors Profile',
            },
        ),
    ]
